<script setup>
import BlocoFilme from "../components/BlocoFilme.vue";
import CompRodape from "../components/CompRodape.vue";
</script>

<template>
  <div class="main">
    <div>
      <p>Diretores</p>
    </div>
    <div class="conteudo">
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
    </div>
    <div class="conteudo">
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
    </div>
    <div class="conteudo">
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
    </div>
    <div class="conteudo">
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
      <BlocoFilme />
    </div>
  </div>
  <CompRodape />
</template>
